default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: s
  pool: 5

development:
  <<: *default
  database: test_cr_api_development


test:
  <<: *default
  database: test_cr_api_test
